const pause = Cypress.env('pause')
const pause_2 = Cypress.env('pause_2')
const pause_1 = Cypress.env('pause_1')
//const skyrizi_what_skyrizi_is_title = Cypress.env('skyrizi_what_skyrizi_is_title')

describe('Skyrizi User Journey', function() {
  it('Visits Skyrizi', function() {
    cy.visit('https://www.skyrizi.eu/') 
    Cypress.on('uncaught:exception', (err, runnable) => {
      return false
    })
    cy.viewport(1280, 800)
    cy.wait(pause_2)
    cy.get('#acceptCookieButton').click()
    cy.wait(pause_2)
    cy.get('[href="/uk/en/privacy-and-cookie-policy-page.html"]').click()
    cy.wait(pause_2)
    cy.scrollTo('bottom')
    cy.wait(pause_2)
    cy.get(':nth-child(82) > p > a').click()
    cy.wait(pause_2)
    cy.get('.header-curvature__header > .logo > .logo__inner > .logo__link > .logo__image').click()
    cy.wait(pause_2)
    cy.get('[href="/uk/en/terms-of-use-page.html"]').click()
    cy.wait(pause_2)
    cy.get('.header-curvature__header > .logo > .logo__inner > .logo__link > .logo__image').click()
    cy.wait(pause_2)
  //Selects country from country dropdown
  cy.get('#select_country').click()
  cy.get('[style="max-height: 411px;"]').scrollTo('bottom')
  cy.wait(pause_2)
  cy.get(':nth-child(26) > :nth-child(1)').click()
  cy.wait(pause_2)
  cy.get('.active').click()
  cy.wait(pause_2)
  cy.get(':nth-child(29) > .pointer').click()
  cy.wait(pause_2)
  cy.get(':nth-child(1) > .product > .product__inner > .product-box-footer > .button > .button__wrapper > .hyphenate').click()
  cy.wait(pause_2)
  cy.get('.header-area__left > :nth-child(1) > .logo__inner > :nth-child(1) > .logo__image').click()
  cy.wait(pause_2)
  cy.get(':nth-child(1) > .product > .product__inner > .product-image > .image > a > img').click()
  cy.wait(pause_2)
  cy.get('.header-area__caution > .cmp > p > a').click()
  cy.wait(pause_2)
  cy.get(':nth-child(1) > .product > .product__inner > .product-logo > .image > a > img').click()
  cy.wait(pause_2)
  cy.get('.header-area__left > :nth-child(1) > .logo__inner > :nth-child(1) > .logo__image').click()
  cy.wait(pause_2)
  cy.get('a > .text-primary').click()
  cy.wait(pause_2)
  cy.get('.col-md-4 > .image > .lightbox-link').click()
  cy.wait(pause_2)
  cy.get('.lb-close').click()
  cy.wait(pause_2)
  cy.get(':nth-child(2) > .nav-link').click()
  cy.wait(pause_2)
  cy.get(':nth-child(3) > .nav-link').click()
  cy.wait(pause_2)
  cy.get(':nth-child(4) > .nav-link').click()
  cy.wait(pause_2)
  cy.get(':nth-child(5) > .nav-link').click()
  cy.wait(pause_2)
  cy.get(':nth-child(6) > .nav-link').click()
  cy.wait(pause_2)
  cy.get(':nth-child(7) > .nav-link').click()
  cy.wait(pause_2)
  cy.get('.vjs-poster').click('center', { force: true })
  cy.wait(pause_1)
  cy.get('.vjs-poster').click('center', { force: true })
  cy.wait(pause_2)
  cy.get(':nth-child(8) > .nav-link').click()
  cy.wait(pause_2)
  cy.get('.container > .button > .button__wrapper > .hyphenate').click()
//cy.get('.container div h3 span').should('have.text',skyrizi_what_you_need_to_know_title)
  
  })         
})